### ISSUE TITLE
Hi, guru, There is a bug in common.GetEndPoint() if git pulled the latest delphereum.

### ISSUE THREAD

**Issue by gneowing** [svanas/PubSub#1]
Hi, guru,
 I git pulled the delphereum.
And applied https://github.com/IndySockets/OpenSSL-Binaries and the trial version form https://www.esegece.com/websockets/download.
There is a compile error:
![2023-05-18 110049](https://github.com/svanas/PubSub/assets/11737423/f8136d9d-f481-4c88-ac33-a70c27a86b18)

**Comment by svanas** [comment]
@gneowing please pull and try again
