### ISSUE TITLE
Hi,guru, if enable the proxy of TsgcWebSocketClient, while Alchemy, it failed.

### ISSUE THREAD

**Issue by gneowing** [svanas/PubSub#3]
![image](https://github.com/svanas/PubSub/assets/11737423/c298650a-1d9d-438f-be9c-96e5c1b0361c)

refer to the latest comments  of  https://github.com/svanas/PubSub/issues/2
And my workaround:
![image](https://github.com/svanas/PubSub/assets/11737423/a5a207a4-7f4b-49ed-bd16-2fdc8a67af51)

**Comment by svanas** [comment]
Fixed in https://github.com/svanas/delphereum/commit/58a688c3ebd28ee36a847d0b1d96cfd35a59a249

**Comment by gneowing** [comment]
I have to modify common.pas  in my VPN env.
![image](https://github.com/svanas/PubSub/assets/11737423/fe6cb49f-6f72-42d3-8c15-734a4bd3f284)
